# Generated by Django 5.0.6 on 2024-08-06 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_usuario_managers_diaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaria',
            name='data_atendimento',
            field=models.DateTimeField(),
        ),
    ]
