# Generated by Django 5.0.6 on 2024-08-06 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_diaria_data_atendimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaria',
            name='complemento',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
