# Generated by Django 3.2.10 on 2024-09-18 21:58

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_avaliacaodiaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto_documento',
            field=models.ImageField(null=True, upload_to=api.models.nome_arquivo_documento, validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto_usuario',
            field=models.ImageField(null=True, upload_to=api.models.nome_arquivo_foto, validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
